### PR TITLE
Remove link to ASF-wide security page from the menu

### PR DESCRIPTION
**Pull request by raboof**
To make the link to the project-specific security page (which links to the ASF-wide security page, but also adds project-specific information) more prominent.

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
If we removed this link, where can we get security link in seatunnel website page?

**Comment by raboof** [comment]
This should only remove the 'Security' link in the 'ASF' submenu, not the top-level 'Security' link that points to https://seatunnel.apache.org/security

**Comment by Hisoka-X** [comment]
> This should only remove the 'Security' link in the 'ASF' submenu, not the top-level 'Security' link that points to https://seatunnel.apache.org/security

Oh, I got it.

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @raboof

**Pull request merged**
